name: 05 - vars Context

on:
  push:
  workflow_dispatch:

jobs:
  vars_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print vars context variables
        run: |
          echo "APP_ENV from vars context = ${{ vars.APP_ENV }}"
